name: ninte
description: An end-to-end encrypted habit-building and productivity app.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  # State Management
  flutter_bloc: ^8.1.3
  # Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  # Encryption
  encrypt: ^5.0.3
  # Dependency Injection
  get_it: ^7.6.7
  # Functional Programming
  dartz: ^0.10.1
  # API Client
  dio: ^5.4.0
  # UI and Styling
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  shimmer: ^3.0.0
  # Others
  equatable: ^2.0.5
  intl: ^0.19.0
  uuid: ^4.3.3
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.8
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/ 