name: ninte
description: A modern habit tracking app built with Flutter.
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_riverpod: ^2.4.9
  flutter_bloc: ^8.1.3
  shared_preferences: ^2.2.2
  equatable: ^2.0.5
  shimmer: ^3.0.0
  intl: ^0.19.0
  path_provider: ^2.1.1
  sqflite: ^2.3.0
  uuid: ^4.2.2
  
  # Firebase
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  firebase_storage: ^11.5.6
  flutter_svg: ^2.0.9
  google_sign_in: ^6.1.6
  just_audio: ^0.9.36
  awesome_notifications: ^0.8.2
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  confetti: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.7
  mockito: ^5.4.4
  test: ^1.24.9
  freezed: ^2.4.5
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/logo/
    - assets/sounds/tick.mp3
    - assets/sounds/timer_complete.mp3