library app_theme;

import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'app_theme_data.dart';

// Theme types enum
enum ThemeType {
  midnight,
  eclipse,
  aurora,
  sunset,
  ocean,
  lavender,
  emerald,
  ruby,
  sapphire,
  amethyst,
  obsidian,
  neon,
  forest,
  cosmic,
  desert,
  pearl,
  glacier,
  vanilla,
  mint,
  rose,
  moonlight,
  porcelain,
  champagne,
  cotton,
  crystal,
}

// Theme tags enum
enum ThemeTag {
  dark,
  light,
  oled,
  colorful,
  minimal,
  elegant,
  nature,
  modern,
  warm,
  cool,
  highContrast,
}

// Theme metadata class
class ThemeMetadata {
  final String name;
  final String description;
  final List<ThemeTag> tags;

  const ThemeMetadata({
    required this.name,
    required this.description,
    required this.tags,
  });
}

// Theme management
class AppTheme {
  static final Map<ThemeType, AppThemeData> themes = {
    ThemeType.midnight: const AppThemeData(
      name: 'Midnight Blue',
      description: 'Deep blue theme with a professional look',
      tags: [ThemeTag.dark, ThemeTag.elegant, ThemeTag.cool],
      background: Color(0xFF0A0E1A),
      surface: Color(0xFF141927),
      surfaceLight: Color(0xFF1E2433),
      accent: Color(0xFF4A9FFF),
      accentLight: Color(0xFF6FB4FF),
      accentSecondary: Color(0xFF7F5AF0),
      textPrimary: Color(0xFFFFFFFF),
      textSecondary: Color(0xFFB4B4BB),
      textTertiary: Color(0xFF8E8E96),
      error: Color(0xFFE53935),
      success: Color(0xFF4CAF50),
      warning: Color(0xFFFFB300),
    ),
    ThemeType.eclipse: const AppThemeData(
      name: 'Eclipse Dark',
      description: 'Classic dark theme with orange accents',
      tags: [ThemeTag.dark, ThemeTag.modern, ThemeTag.warm],
      background: Color(0xFF1C1B1F),
      surface: Color(0xFF252429),
      surfaceLight: Color(0xFF2D2C31),
      accent: Color(0xFFFF6B4A),
      accentLight: Color(0xFFFF8A6F),
      accentSecondary: Color(0xFF7F5AF0),
      textPrimary: Color(0xFFFFFFFF),
      textSecondary: Color(0xFFB4B4BB),
      textTertiary: Color(0xFF8E8E96),
      error: Color(0xFFE53935),
      success: Color(0xFF4CAF50),
      warning: Color(0xFFFFB300),
    ),
    ThemeType.aurora: const AppThemeData(
      name: 'Aurora Green',
      description: 'Nature-inspired theme with vibrant greens',
      tags: [ThemeTag.dark, ThemeTag.nature, ThemeTag.colorful],
      background: Color(0xFF0F1720),
      surface: Color(0xFF1A222B),
      surfaceLight: Color(0xFF252D36),
      accent: Color(0xFF4ADE80),
      accentLight: Color(0xFF86EFAC),
      accentSecondary: Color(0xFF60A5FA),
      textPrimary: Color(0xFFFFFFFF),
      textSecondary: Color(0xFFB4B4BB),
      textTertiary: Color(0xFF8E8E96),
      error: Color(0xFFE53935),
      success: Color(0xFF4CAF50),
      warning: Color(0xFFFFB300),
    ),
    ThemeType.sunset: const AppThemeData(
      name: 'Sunset Orange',
      description: 'Warm and vibrant theme inspired by dusk',
      tags: [ThemeTag.dark, ThemeTag.warm, ThemeTag.colorful],
      background: Color(0xFF1A1618),
      surface: Color(0xFF251F21),
      surfaceLight: Color(0xFF312A2C),
      accent: Color(0xFFF97316),
      accentLight: Color(0xFFFB923C),
      accentSecondary: Color(0xFFE11D48),
      textPrimary: Color(0xFFFFFFFF),
      textSecondary: Color(0xFFB4B4BB),
      textTertiary: Color(0xFF8E8E96),
      error: Color(0xFFE53935),
      success: Color(0xFF4CAF50),
      warning: Color(0xFFFFB300),
    ),
    ThemeType.ocean: const AppThemeData(
      name: 'Ocean Blue',
      description: 'Deep sea-inspired theme with calming blues',
      tags: [ThemeTag.dark, ThemeTag.nature, ThemeTag.cool],
      background: Color(0xFF0D1B2A),
      surface: Color(0xFF162635),
      surfaceLight: Color(0xFF1F3140),
      accent: Color(0xFF06B6D4),
      accentLight: Color(0xFF22D3EE),
      accentSecondary: Color(0xFF3B82F6),
      textPrimary: Color(0xFFFFFFFF),
      textSecondary: Color(0xFFB4B4BB),
      textTertiary: Color(0xFF8E8E96),
      error: Color(0xFFE53935),
      success: Color(0xFF4CAF50),
      warning: Color(0xFFFFB300),
    ),
    ThemeType.lavender: const AppThemeData(
      name: 'Lavender Purple',
      description: 'Elegant purple theme with soft accents',
      tags: [ThemeTag.dark, ThemeTag.elegant, ThemeTag.colorful],
      background: Color(0xFF1A1625),
      surface: Color(0xFF251F31),
      surfaceLight: Color(0xFF312A3D),
      accent: Color(0xFF8B5CF6),
      accentLight: Color(0xFFA78BFA),
      accentSecondary: Color(0xFFE879F9),
      textPrimary: Color(0xFFFFFFFF),
      textSecondary: Color(0xFFB4B4BB),
      textTertiary: Color(0xFF8E8E96),
      error: Color(0xFFE53935),
      success: Color(0xFF4CAF50),
      warning: Color(0xFFFFB300),
    ),
    ThemeType.emerald: const AppThemeData(
      name: 'Emerald Green',
      description: 'Rich green theme with natural tones',
      tags: [ThemeTag.dark, ThemeTag.nature, ThemeTag.elegant],
      background: Color(0xFF0F1A17),
      surface: Color(0xFF1A2522),
      surfaceLight: Color(0xFF25302D),
      accent: Color(0xFF10B981),
      accentLight: Color(0xFF34D399),
      accentSecondary: Color(0xFF059669),
      textPrimary: Color(0xFFFFFFFF),
      textSecondary: Color(0xFFB4B4BB),
      textTertiary: Color(0xFF8E8E96),
      error: Color(0xFFE53935),
      success: Color(0xFF4CAF50),
      warning: Color(0xFFFFB300),
    ),
    ThemeType.ruby: const AppThemeData(
      name: 'Ruby Red',
      description: 'Bold and passionate red theme',
      tags: [ThemeTag.dark, ThemeTag.colorful, ThemeTag.warm],
      background: Color(0xFF1A1516),
      surface: Color(0xFF251D1E),
      surfaceLight: Color(0xFF312627),
      accent: Color(0xFFEF4444),
      accentLight: Color(0xFFF87171),
      accentSecondary: Color(0xFFDC2626),
      textPrimary: Color(0xFFFFFFFF),
      textSecondary: Color(0xFFB4B4BB),
      textTertiary: Color(0xFF8E8E96),
      error: Color(0xFFE53935),
      success: Color(0xFF4CAF50),
      warning: Color(0xFFFFB300),
    ),
    ThemeType.sapphire: const AppThemeData(
      name: 'Sapphire Blue',
      description: 'Deep and luxurious blue theme',
      tags: [ThemeTag.dark, ThemeTag.elegant, ThemeTag.cool],
      background: Color(0xFF0F172A),
      surface: Color(0xFF1E293B),
      surfaceLight: Color(0xFF334155),
      accent: Color(0xFF3B82F6),
      accentLight: Color(0xFF60A5FA),
      accentSecondary: Color(0xFF2563EB),
      textPrimary: Color(0xFFFFFFFF),
      textSecondary: Color(0xFFB4B4BB),
      textTertiary: Color(0xFF8E8E96),
      error: Color(0xFFE53935),
      success: Color(0xFF4CAF50),
      warning: Color(0xFFFFB300),
    ),
    ThemeType.amethyst: const AppThemeData(
      name: 'Amethyst Purple',
      description: 'Rich purple theme with royal accents',
      tags: [ThemeTag.dark, ThemeTag.elegant, ThemeTag.colorful],
      background: Color(0xFF1E1B2E),
      surface: Color(0xFF2A2640),
      surfaceLight: Color(0xFF363152),
      accent: Color(0xFFA855F7),
      accentLight: Color(0xFFD946EF),
      accentSecondary: Color(0xFF9333EA),
      textPrimary: Color(0xFFFFFFFF),
      textSecondary: Color(0xFFB4B4BB),
      textTertiary: Color(0xFF8E8E96),
      error: Color(0xFFE53935),
      success: Color(0xFF4CAF50),
      warning: Color(0xFFFFB300),
    ),
    ThemeType.obsidian: const AppThemeData(
      name: 'Obsidian Glass',
      description: 'Pure black theme optimized for OLED displays',
      tags: [ThemeTag.dark, ThemeTag.oled, ThemeTag.minimal, ThemeTag.highContrast],
      background: Color(0xFF000000),
      surface: Color(0xFF111111),
      surfaceLight: Color(0xFF1A1A1A),
      accent: Color(0x67FFFFFF),
      accentLight: Color(0x90F6F7F9),
      accentSecondary: Color(0xFFBDBDBD),
      textPrimary: Color(0xFFFFFFFF),
      textSecondary: Color(0xFFE0E0E0),
      textTertiary: Color(0xFFBDBDBD),
      error: Color(0xFFFF5252),
      success: Color(0xFF69F0AE),
      warning: Color(0xFFFFD740),
    ),
    ThemeType.neon: const AppThemeData(
      name: 'Neon Pulse',
      description: 'Vibrant cyberpunk-inspired theme with neon accents',
      tags: [ThemeTag.dark, ThemeTag.colorful, ThemeTag.modern],
      background: Color(0xFF0A0A0F),
      surface: Color(0xFF141419),
      surfaceLight: Color(0xFF1E1E24),
      accent: Color(0xFF00FF9C),
      accentLight: Color(0xFF80FFD9),
      accentSecondary: Color(0xFFFF00FF),
      textPrimary: Color(0xFFFFFFFF),
      textSecondary: Color(0xFFB4B4BB),
      textTertiary: Color(0xFF8E8E96),
      error: Color(0xFFFF355E),
      success: Color(0xFF39FF14),
      warning: Color(0xFFFFE202),
    ),
    ThemeType.forest: const AppThemeData(
      name: 'Deep Forest',
      description: 'Nature-inspired dark theme with earthy tones',
      tags: [ThemeTag.dark, ThemeTag.nature, ThemeTag.elegant],
      background: Color(0xFF0B1512),
      surface: Color(0xFF132018),
      surfaceLight: Color(0xFF1B2922),
      accent: Color(0xFF2ECC71),
      accentLight: Color(0xFF7DCEA0),
      accentSecondary: Color(0xFFE67E22),
      textPrimary: Color(0xFFE8F6F3),
      textSecondary: Color(0xFFB4C7C2),
      textTertiary: Color(0xFF889995),
      error: Color(0xFFE74C3C),
      success: Color(0xFF27AE60),
      warning: Color(0xFFF39C12),
    ),
    ThemeType.cosmic: const AppThemeData(
      name: 'Cosmic Dream',
      description: 'Space-inspired theme with stellar accents',
      tags: [ThemeTag.dark, ThemeTag.modern, ThemeTag.colorful],
      background: Color(0xFF0D0221),
      surface: Color(0xFF1A0B2E),
      surfaceLight: Color(0xFF261439),
      accent: Color(0xFF9D4EDD),
      accentLight: Color(0xFFC77DFF),
      accentSecondary: Color(0xFF00B4D8),
      textPrimary: Color(0xFFF2E9FF),
      textSecondary: Color(0xFFCCB6E6),
      textTertiary: Color(0xFF9B8AAC),
      error: Color(0xFFFF5C8A),
      success: Color(0xFF00F5D4),
      warning: Color(0xFFFFBE0B),
    ),
    ThemeType.desert: const AppThemeData(
      name: 'Desert Sands',
      description: 'Warm desert-inspired theme with sandy tones',
      tags: [ThemeTag.dark, ThemeTag.nature, ThemeTag.warm],
      background: Color(0xFF1A1710),
      surface: Color(0xFF241F16),
      surfaceLight: Color(0xFF2E271B),
      accent: Color(0xFFE6B89C),
      accentLight: Color(0xFFFFD9B8),
      accentSecondary: Color(0xFFDE6B48),
      textPrimary: Color(0xFFF5E6D3),
      textSecondary: Color(0xFFD4C3B0),
      textTertiary: Color(0xFFB3A08E),
      error: Color(0xFFD63447),
      success: Color(0xFF9BC53D),
      warning: Color(0xFFFAC05E),
    ),
    ThemeType.pearl: const AppThemeData(
      name: 'Pearl White',
      description: 'Clean and modern light theme',
      tags: [ThemeTag.light, ThemeTag.minimal, ThemeTag.modern],
      background: Color(0xFFFAFAFA),
      surface: Color(0xFFFFFFFF),
      surfaceLight: Color(0xFFF5F5F5),
      accent: Color(0xFF2196F3),
      accentLight: Color(0xFF64B5F6),
      accentSecondary: Color(0xFF1976D2),
      textPrimary: Color(0xFF1A1A1A),
      textSecondary: Color(0xFF757575),
      textTertiary: Color(0xFFBDBDBD),
      error: Color(0xFFE53935),
      success: Color(0xFF43A047),
      warning: Color(0xFFFFA000),
    ),
    ThemeType.glacier: const AppThemeData(
      name: 'Arctic Glacier',
      description: 'Cool and refreshing ice-inspired theme',
      tags: [ThemeTag.light, ThemeTag.cool, ThemeTag.modern],
      background: Color(0xFFEEF5FF),
      surface: Color(0xFFFFFFFF),
      surfaceLight: Color(0xFFF0F7FF),
      accent: Color(0xFF0288D1),
      accentLight: Color(0xFF4FC3F7),
      accentSecondary: Color(0xFF01579B),
      textPrimary: Color(0xFF102A43),
      textSecondary: Color(0xFF486581),
      textTertiary: Color(0xFF829AB1),
      error: Color(0xFFD32F2F),
      success: Color(0xFF2E7D32),
      warning: Color(0xFFFF8F00),
    ),
    ThemeType.vanilla: const AppThemeData(
      name: 'Vanilla Dream',
      description: 'Warm and cozy light theme',
      tags: [ThemeTag.light, ThemeTag.warm, ThemeTag.elegant],
      background: Color(0xFFFFFBF5),
      surface: Color(0xFFFFFFFF),
      surfaceLight: Color(0xFFFFF8EE),
      accent: Color(0xFFFF9800),
      accentLight: Color(0xFFFFB74D),
      accentSecondary: Color(0xFFF57C00),
      textPrimary: Color(0xFF2D1810),
      textSecondary: Color(0xFF7D5B50),
      textTertiary: Color(0xFFBE9B89),
      error: Color(0xFFC62828),
      success: Color(0xFF388E3C),
      warning: Color(0xFFFFB300),
    ),
    ThemeType.mint: const AppThemeData(
      name: 'Fresh Mint',
      description: 'Fresh and crisp mint-inspired theme',
      tags: [ThemeTag.light, ThemeTag.nature, ThemeTag.cool],
      background: Color(0xFFF2F9F5),
      surface: Color(0xFFFFFFFF),
      surfaceLight: Color(0xFFF0F9F4),
      accent: Color(0xFF00BFA5),
      accentLight: Color(0xFF4DB6AC),
      accentSecondary: Color(0xFF00897B),
      textPrimary: Color(0xFF0A2F25),
      textSecondary: Color(0xFF4A766C),
      textTertiary: Color(0xFF89AEA6),
      error: Color(0xFFD50000),
      success: Color(0xFF00C853),
      warning: Color(0xFFFFAB00),
    ),
    ThemeType.rose: const AppThemeData(
      name: 'Rose Quartz',
      description: 'Soft and delicate pink theme',
      tags: [ThemeTag.light, ThemeTag.elegant, ThemeTag.warm],
      background: Color(0xFFFFF5F7),
      surface: Color(0xFFFFFFFF),
      surfaceLight: Color(0xFFFFF0F3),
      accent: Color(0xFFEC407A),
      accentLight: Color(0xFFF48FB1),
      accentSecondary: Color(0xFFD81B60),
      textPrimary: Color(0xFF2B161D),
      textSecondary: Color(0xFF805A65),
      textTertiary: Color(0xFFBF8F9B),
      error: Color(0xFFC2185B),
      success: Color(0xFF00BFA5),
      warning: Color(0xFFFF8F00),
    ),
    ThemeType.moonlight: const AppThemeData(
      name: 'Moonlight Silver',
      description: 'Elegant silver-toned light theme',
      tags: [ThemeTag.light, ThemeTag.elegant, ThemeTag.modern],
      background: Color(0xFFF8F9FA),
      surface: Color(0xFFFFFFFF),
      surfaceLight: Color(0xFFF1F3F5),
      accent: Color(0xFF5C6BC0),
      accentLight: Color(0xFF7986CB),
      accentSecondary: Color(0xFF3F51B5),
      textPrimary: Color(0xFF2C3E50),
      textSecondary: Color(0xFF546E7A),
      textTertiary: Color(0xFF90A4AE),
      error: Color(0xFFE53935),
      success: Color(0xFF2E7D32),
      warning: Color(0xFFFFA000),
    ),
    ThemeType.porcelain: const AppThemeData(
      name: 'Pure Porcelain',
      description: 'Minimalist black and white theme',
      tags: [ThemeTag.light, ThemeTag.minimal, ThemeTag.highContrast],
      background: Color(0xFFFFFFFF),
      surface: Color(0xFFFCFCFC),
      surfaceLight: Color(0xFFF5F5F5),
      accent: Color(0xFF3F51B5),
      accentLight: Color(0xFF5C6BC0),
      accentSecondary: Color(0xFF303F9F),
      textPrimary: Color(0xFF2C3E50),
      textSecondary: Color(0xFF546E7A),
      textTertiary: Color(0xFF90A4AE),
      error: Color(0xFFD32F2F),
      success: Color(0xFF388E3C),
      warning: Color(0xFFFFA000),
    ),
    ThemeType.champagne: const AppThemeData(
      name: 'Champagne Gold',
      description: 'Luxurious gold-accented light theme',
      tags: [ThemeTag.light, ThemeTag.elegant, ThemeTag.warm],
      background: Color(0xFFFFFBF5),
      surface: Color(0xFFFFFFFF),
      surfaceLight: Color(0xFFFFF8EC),
      accent: Color(0xFFBF9B30),
      accentLight: Color(0xFFD4AF37),
      accentSecondary: Color(0xFFC9A959),
      textPrimary: Color(0xFF33291F),
      textSecondary: Color(0xFF7D6E5B),
      textTertiary: Color(0xFFBBAA91),
      error: Color(0xFFC62828),
      success: Color(0xFF2E7D32),
      warning: Color(0xFFFF8F00),
    ),
    ThemeType.cotton: const AppThemeData(
      name: 'Cotton Cloud',
      description: 'Soft and neutral light theme',
      tags: [ThemeTag.light, ThemeTag.minimal, ThemeTag.elegant],
      background: Color(0xFFFAFAFC),
      surface: Color(0xFFFFFFFF),
      surfaceLight: Color(0xFFF5F5F9),
      accent: Color(0xFF6B7280),
      accentLight: Color(0xFF9CA3AF),
      accentSecondary: Color(0xFF4B5563),
      textPrimary: Color(0xFF1F2937),
      textSecondary: Color(0xFF6B7280),
      textTertiary: Color(0xFFD1D5DB),
      error: Color(0xFFDC2626),
      success: Color(0xFF059669),
      warning: Color(0xFFD97706),
    ),
    ThemeType.crystal: const AppThemeData(
      name: 'Crystal Clear',
      description: 'Modern white theme with crisp blue accents',
      tags: [ThemeTag.light, ThemeTag.modern, ThemeTag.cool],
      background: Color(0xFFF8FAFC),
      surface: Color(0xFFFFFFFF),
      surfaceLight: Color(0xFFF1F5F9),
      accent: Color(0xFF0EA5E9),
      accentLight: Color(0xFF38BDF8),
      accentSecondary: Color(0xFF0284C7),
      textPrimary: Color(0xFF0F172A),
      textSecondary: Color(0xFF475569),
      textTertiary: Color(0xFF94A3B8),
      error: Color(0xFFE11D48),
      success: Color(0xFF10B981),
      warning: Color(0xFFF59E0B),
    ),
  };

  static final defaultTheme = themes[ThemeType.eclipse]!;

  static void setSystemUIOverlayStyle(AppThemeData theme) {
    SystemChrome.setSystemUIOverlayStyle(
      SystemUiOverlayStyle(
        statusBarColor: Colors.transparent,
        statusBarIconBrightness: Brightness.light,
        systemNavigationBarColor: theme.background,
        systemNavigationBarIconBrightness: Brightness.light,
        systemNavigationBarDividerColor: Colors.transparent,
      ),
    );
  }
} 